<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>$(AppTestTargetFramework)</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="$(TestSdk)" />
        <PackageReference Include="xunit.v3" Version="$(XUnitVersion)" />
        <PackageReference Include="xunit.runner.visualstudio" Version="2.8.*">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="coverlet.collector" Version="6.*">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="FluentAssertions" Version="6.8.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Juice.Workflows.Designer\Juice.Workflows.Designer.csproj" />
        <ProjectReference Include="..\..\src\Juice.Workflows\Juice.Workflows.csproj" />
        <ProjectReference Include="..\..\src\Juice.Workflows.Bpmn\Juice.Workflows.Bpmn.csproj" />
        <ProjectReference Include="..\..\src\Juice.Workflows.Yaml\Juice.Workflows.Yaml.csproj" />
    </ItemGroup>

</Project>
